app/STalent/config/routes.rb
Rails.application.routes.draw do
  resources :profesional_profiles
  resources :lenguages
  resources :educations
  resources :computer_skills
  resources :profesional_experiences
  resources :curriculums
  resources :companies do
    resources :jobs
  end
  devise_for :users
  get 'welcome/index'
  root 'welcome#index'
  

  get 'jobs/', to: 'jobs#all' , as: 'jobs'

end

app/STalent/app/models/job.rb
class Job < ActiveRecord::Base
	validates :title, presence: true
	validates :description, presence: true, length: { minimum: 20 }
	validates :minimumEducation, presence: true
	validates :yearExperience, presence: true
	validates :lenguages, presence: true
	belongs_to :company
end

app/STalent/app/controllers/jobs_controller.rb
class JobsController < ApplicationController
	layout 'dashboard'
	before_action :set_company, except: [:all]
	before_action :authenticate_user! , except: [:all,:index,:show]
	#GET /jobs/all

	def all
		@jobs = Job.all
	end
	#GET /jobs
	def index
		@jobs = Job.all
	end

	#GET /jobs/:id
	def show
		@job = Job.find(params[:id])
	end

	def new
		@job = Job.new()


	end
	#POST /jobs
	def create
		@job = Job.new(job_params)
		@job.company = @company
		if @job.save
			redirect_to @job.company
		else
			render :new
		end

	end

	#PUT /jobs/:id
	def update
		@job = Job.find(params[:id])
		if @job.update(job_params)
			redirect_to @job.company
		else
			render :edit
		end
	end


	def edit
		@job = Job.find(params[:id])
	end

	def destroy
		@job = Job.find(params[:id])
		@job.destroy
		redirect_to @company
	end

	private
	def set_company
		@company = Company.find(params[:company_id])
	end
	def job_params
		params.require(:job).permit(:title , :salary, :description , :recruitmentTime, :minimumEducation ,:yearExperience ,:lenguages ,:other)
	end

end

app/STalent/app/views/jobs/_form.html.erb
<div class="Form">
  <div class="Form-top">
    <% name ||= "Crear" %>
    <p class="Form-mainTitle"><%= name %> Empleo</p>
    <p class="Form-secondaryTitle"> Completa todos los campos sobre el empleo </p>
    <p id="notice"><%= notice %></p>
  </div>
  <%= form_for([@company,@job]) do |f| %>
   <% if @job.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@job.errors.count, "error") %> prohibited this company from being saved:</h2>

          <ul>
          <% @job.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
  <div class="Form-bot">
    <div class="Form-field">
      <%= f.label :title , "Titulo", class: "Form-label" %>
      <%= f.text_field :title, class: "Form-input" , :required => true %> 
    </div>
    <div class="Form-field">
      <%= f.label :salary , "Salario", class: "Form-label"  %>
      <%= f.text_field :salary, class: "Form-input"%> 
    </div>
     <div class="Form-field">
      <%= f.label :description , "Descripción", class: "Form-label"%>
      <%= f.text_area(:description, class: "Form-inputArea", rows: 8)%> 
    </div>
    <div class="Form-field">
      <%= f.label :recruitmentTime , "Tiempo de reclutamiento", class: "Form-label"%>
      <%= f.text_field :recruitmentTime, class: "Form-input" %> 
    </div>
    <div class="Form-field">
      <%= f.label :minimumEducation , "Educación Minima", class: "Form-label"%>
      <%= f.text_field :minimumEducation, class: "Form-input" %> 
    </div>
    <div class="Form-field">
      <%= f.label :yearExperience , "Años de Experiencia", class: "Form-label"%>
      <%= f.text_field :yearExperience, class: "Form-input" %> 
    </div>
     <div class="Form-field">
      <%= f.label :lenguages , "Idiomas ", class: "Form-label"%>
      <%= f.text_field :lenguages, class: "Form-input" %> 
    </div>
    <div class="Form-field">
      <%= f.label :other , "Otros", class: "Form-label"%>
      <%= f.text_area(:other, class: "Form-inputArea" , rows: 8)%> 
    </div>
    <div class="Form-field">
      <div class="Button">
        <%= f.submit "Guardar", class: "Button--saveForm" %>  
      </div>
    </div>
  </div>
  <% end %>
</div>

app/STalent/app/views/jobs/all.html.erb
    <div class="LayoutDashboard-jobs">
      <section class="Information">
        <p class="Information-mainText">Ofertas sugeridas según tu perfil profesional</p>
      </section>
      <section class="Jobs">
        <%@jobs.each do |job| %>
        <div class="Job">
          <div class="Job-avatar">
            <p class="Job-avatarText"><%= job.company.name[0] %></p>
          </div>
          <div class="Job-content">
            <%= link_to job.title ,company_job_path(job.company, job), class: "Job-title" %>
            <%= link_to job.company.name , company_path(job.company), class: "Job-company" %>
            <p class="Job-time"><%= DateTime.now.beginning_of_day   %></p>
            <p class="Job-salary">
            <% if job.salary == 0 %>
              Indefinido 
            <% else %>
              <span> S/. </span> <%= job.salary %> <span>.00</span>             
            <% end %>
            </p>
            <p class="Job-date">Publicado el 
              <%= job.created_at.strftime("%d %b")  
              %>
            </p>
          </div>
          <div class="Job-menuActions">
            <div class="Button"><a href="#" class="Button--apply">Aplicar</a></div>
          </div>
        </div>
        <% end %>
       </section>
      <div class="LayoutDashboard-more">
        <div class="Button"><a href="#" class="Button--green">Mas sugerencias para mí </a></div>
      </div>
    </div>
  

app/STalent/app/views/jobs/edit.html.erb
<div class="LayoutDashboard-normal">
  <%= render "form" , name: 'Editar '%>
</div>

app/STalent/app/views/jobs/index.html.erb
    <div class="LayoutDashboard-jobs">
      <section class="Information">
        <p class="Information-mainText">Ofertas sugeridas según tu perfil profesional</p>
      </section>
      <section class="Jobs">
        <% @jobs.each do |job| %>
        <div class="Job">
          <div class="Job-avatar">
            <p class="Job-avatarText">L</p>
          </div>
          <div class="Job-content"><%= link_to job.title, job , class: "Job-title" %>
            <h5 class="Job-company">LimaW SAC</h5>
            <p class="Job-time"><%= DateTime.now.beginning_of_day   %></p>
            <p class="Job-salary">
            <% if job.salary == 0 %>
              Indefinido 
            <% else %>
              <span> S/. </span> <%= job.salary %> <span>.00</span>             
            <% end %>
            </p>
            <p class="Job-date">Publicado el 
              <%= job.created_at.strftime("%d %b")  
              %>
            </p>
          </div>
          <div class="Job-menuActions">
            <div class="Button"><a href="#" class="Button--apply">Aplicar</a></div>
          </div>
        </div>
        <% end %>
       </section>
      <div class="LayoutDashboard-more">
        <div class="Button"><a href="#" class="Button--green">Mas sugerencias para mí	</a></div>
      </div>
    </div>
  

app/STalent/app/views/jobs/new.html.erb
<div class="LayoutDashboard-normal">
  	<%= render "form" %>
</div>

app/STalent/app/views/jobs/show.html.erb
  <div class="LayoutDashboard-informationJob">
    <section class="Information">
      <p class="Information-mainText">Información de Perfil</p>
    </section>
    <div class="InformationJob">
      <div class="InformationJob-top">
        <div class="InformationJob-avatar">
          <p class="InformationJob-avatarText">L</p>
        </div>
        <div class="InformationJob-textHeader"><a href="" class="InformationJob-title"><%= @job.title %></a>
          <p class="InformationJob-company">LimaW SAC</p>
        </div>
      </div>
      <div class="InformationJob-middle">
        <p class="InformationJob-date"><%= @job.title %></p>
        <p class="InformationJob-calendar">Indefinido</p>
        <p class="InformationJob-typeContract">Contrato</p>
        <p class="InformationJob-workHours">Completo</p>
      </div>
      <div class="InformationJob-bottom">
        <p class="InformationJob-descriptionText">Descripción</p>
        <div class="InformationJob-description"> 
          <p class="InformationJob-textDescription"><%= @job.description %></p>
        </div>
        <p class="InformationJob-requirements">Requerimientos</p>
        <p class="InformationJob-minimumEducation">Educacion Minima :<span class="InformationJob-textEducation"><%= @job.minimumEducation %></span></p>
        <p class="InformationJob-yearExperience">Años de experiencia : <span class="InformationJob-textExperience"><%= @job.yearExperience %></span></p>
        <p class="InformationJob-lenguaje">Idioma : <span class="InformationJob-textLenguaje"><%= @job.lenguages %></span></p>
        <p class="InformationJob-travel">Disponibilidad de Viajar : <span class="InformationJob-textTravel">No</span></p>
        <p class="InformationJob-changeResidence">Disponibilidad de Cambio de residencia : <span class="InformationJob-textResidence">No</span></p>
      </div>
    </div>
  </div>
  <div class="LayoutDashboard-apply">
    <div class="Button"><a href="" class="Button--fixedGreen">Aplicar</a></div>
  </div>