app/STalent/config/routes.rb
Rails.application.routes.draw do
  resources :profesional_profiles
  resources :lenguages
  resources :educations
  resources :computer_skills
  resources :profesional_experiences
  resources :curriculums
  resources :companies do
    resources :jobs
  end
  devise_for :users
  get 'welcome/index'
  root 'welcome#index'
  

  get 'jobs/', to: 'jobs#all' , as: 'jobs'

end

app/STalent/app/models/company.rb
class Company < ActiveRecord::Base
	has_many :jobs
end

app/STalent/app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  layout 'dashboard'
  before_action :set_company, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user! , except: [:all,:index,:show]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    @job = Job.new
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :photo, :description)
    end
end

app/STalent/app/helpers/companies_helper.rb
module CompaniesHelper
end

app/STalent/app/views/companies/_form.html.erb
<div class="Form">
  <div class="Form-top">
    <% name ||= "Crear" %>
    <p class="Form-mainTitle"><%= name %> Compañia</p>
    <p class="Form-secondaryTitle"> Completa todos los campos sobre la empresa </p>
  </div>
  <div class="Form-bot">
    <%= form_for(@company) do |f| %>
      <% if @company.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

          <ul>
          <% @company.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="Form-field">
        <%= f.label :name , "Nombre *",class: "Form-label" %>
        <%= f.text_field :name , class: "Form-input" %>
      </div>
      <div class="Form-field">
        <%= f.label :photo, "Imagen", class: "Form-label" %>
        <%= f.text_field :photo , class: "Form-input" %>
      </div>
      <div class="Form-field">
        <%= f.label :description, "Descripcion" ,class: "Form-label" %>
        <%= f.text_area :description , class: "Form-inputArea" , rows: 8 %>
      </div>
      <div class="Form-field">
        <div class="Button">
          <%= f.submit "Guardar", class: "Button--saveForm" %>  
        </div>
      </div>
    <% end %>
  </div>
</div>

app/STalent/app/views/companies/edit.html.erb
<%= render 'form' %>

<%= link_to 'Mostar', @company %> |
<%= link_to 'Regresar', companies_path %>

app/STalent/app/views/companies/index.html.erb
<div class="LayoutDashboard-jobs">
      <section class="Information">
        <p class="Information-mainText">Ofertas sugeridas según tu perfil profesional</p>
      </section>
      <p id="notice"><%= notice %></p>
      <section class="Jobs">
          <% @companies.each do |company| %>
            <div class="Job">
              <div class="Job-avatar">
                <p class="Job-avatarText"><%= company.name[0] %></p>
              </div>
            <div class="Job-content">
                <%= link_to company.name,company, class: "Job-title" %>
                <p class="Job-company"> <%= company.description %> </p>
            </div>
            <div class="Job-menuActions">
              <div class="Button">
                <%= link_to 'Añadir Empleos', new_company_job_path(company) , class: "Button--apply" %>
                <%= link_to 'Editar', edit_company_path(company), class: "Button--apply" %>
                <%= link_to 'Borrar', company,class: "Button--apply",  method: :delete, data: { confirm: 'Estas Seguro ?' } %>
              </div>
            </div>  
            </div>
          <% end %>
        </section>
        <div class="Button">
          <%= link_to 'Crear Empresas', new_company_path, class: "Button--green" %>          
        </div>
      </div>



</div>

app/STalent/app/views/companies/new.html.erb
<div class="LayoutDashboard-normal">
	<%= render 'form' %>
	<%= link_to 'Regresar', companies_path %>
</div>

app/STalent/app/views/companies/show.html.erb
<div class="LayoutDashboard-informationJob" ng-controller="jobsController as jobs">
	<section class="Information">
    	<p class="Information-mainText">Información de la Empresa</p>
    	<p id="notice"><%= notice %></p>
    </section>
	<div class="InformationJob">
      <div class="InformationJob-top">
        <div class="InformationJob-avatar">
          <p class="InformationJob-avatarText"><%= @company.name[0] %></p>
        </div>
        <div class="InformationJob-textHeader"><a href="" class="InformationJob-title"><%= @company.name %></a>
          <p class="InformationJob-company"><%= @company.description %></p>
        </div>
      </div>
     </div>
     <div class="InformationJob-bottom">
     	<p class="InformationJob-descriptionText">Empleos</p>
      <section class="Jobs">
        <% @company.jobs.each do |job| %>
        <div class="Job">
          <div class="Job-avatar">
            <p class="Job-avatarText"><%= @company.name[0] %></p>
          </div>
          <div class="Job-content"><%= link_to job.title ,company_job_path(@company.id,job.id), class: "Job-title" %>
            <h5 class="Job-company">LimaW SAC</h5>
            <p class="Job-time"><%= DateTime.now.beginning_of_day   %></p>
            <p class="Job-salary">
            <% if job.salary == 0 %>
              Indefinido 
            <% else %>
              <span> S/. </span> <%= job.salary %> <span>.00</span>             
            <% end %>
            </p>
            <p class="Job-date">Publicado el 
              <%= job.created_at.strftime("%d %b")  
              %>
            </p>
          </div>
          <div class="Job-menuActions">
            
          </div>
        </div>
        <% end %>
       </section>
      <div class="Button">
              <a href="" class="Button--add" ng-click="jobs.toggle()">Añadir empleos</a>
      </div>
      <div class="Job-animate" ng-show="jobs.show">
     	  <%= render "jobs/form" %>
      </div>
     </div>
     
	<%= link_to 'Editar', edit_company_path(@company) %> |
	<%= link_to 'Atrás', companies_path %>
</div>