app/STalent/config/routes.rb
Rails.application.routes.draw do
  resources :profesional_profiles
  resources :lenguages
  resources :educations
  resources :computer_skills
  resources :profesional_experiences
  resources :curriculums
  resources :companies do
    resources :jobs
  end
  devise_for :users
  get 'welcome/index'
  root 'welcome#index'
  

  get 'jobs/', to: 'jobs#all' , as: 'jobs'

end

app/STalent/app/views/layouts/_footer.html.erb
<footer class="LayoutDashboard-footer">
  <div class="Links">
    <p class="Links-mainText">Secciones</p>
    <ul class="Links-list">
      <li class="Links-element"><a href="#" class="Links-text">Mi Curriculum</a></li>
      <li class="Links-element"><a href="#" class="Links-text">Mis Candidaturas</a></li>
      <li class="Links-element"><a href="#" class="Links-text">Mi perfil</a></li>
    </ul>
    <p class="Links-mainText">Empresas</p>
    <ul class="Links-list">
      <li class="Links-element"><a href="#" class="Links-text">Contacto</a></li>
    </ul>
    <div class="Copyright">
      <p class="Copyright-text">(c) 2015 - Psicotalentos SAC. Todos los derechos reservados</p>
    </div>
  </div>
</footer>

app/STalent/app/views/layouts/_header.html.erb
<header class="LayoutDashboard-header">
  <div class="topBarDashboard">
    <div class="topBarDashboard-left">
      <div class="topBarDashboard-logo">
        <div class="Logo">
          <%= link_to jobs_path, class: "Logo-text Logo--minText"  do %>
            <span class="Logo--textLight">Psico</span><span class="Logo--textBold">talentos</span>
          <% end %>       
        </div>
      </div>
    </div>
    <div class="topBarDashboard-right">
      <div class="topBarDashboard-search"><a href="#" class="topBarDashboard-iconSearch"></a></div>
      <div class="topBarDashboard-menuAvatar">
        <% if user_signed_in? %>
          <div class="AvatarProfile">
          <div class="AvatarProfile-avatar">
          <%= link_to curriculums_path do %>
            <%= image_tag("avatar.jpg", class: "AvatarProfile-image") %>
          <%end%>
          </div>
          <div class="Button">
          <%= link_to "Cerrar Sesión" , destroy_user_session_path, class: "Button--session", method: :delete %>
            </li>
          </div>

        </div>
        <% else %>
          <div class="Button">
          <%= link_to "Entrar" , new_user_session_path, class: "Button--session" %>
            </li>
          </div>
        <% end %>
        
      </div>
    </div>
  </div>
  <div class="menuDashboard">
    <ul class="menuDashboard-elements">
      <% if user_signed_in? %>
        <li class="menuDashboard-element">
            <%= link_to "Sugerencias", jobs_path, class: "menuDashboard-text" %>
        </li>
        <li class="menuDashboard-element">
          <%= link_to "Empleos", jobs_path, class: "menuDashboard-text" %>
        </li>
        <li class="menuDashboard-element">
          <a href="#" class="menuDashboard-text">Postulaciones</a>
        </li>
      <% else %>
        <li class="menuDashboard-element">
            <%= link_to "Inicio", root_path, class: "menuDashboard-text" %>
        </li>
        <li class="menuDashboard-element">
          <%= link_to "Empleos", jobs_path, class: "menuDashboard-text" %>
        </li>
      <% end %>

     
    </ul>
  </div>
</header>

app/STalent/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>STalent</title>
  <meta charset="UTF-8"/>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<link href="http://fonts.googleapis.com/css?family=Roboto:500,400italic,100,300,500italic,300italic,400" rel="stylesheet" type="text/css"/>
	<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0"/>
	<%= csrf_meta_tags %>
</head>
<body ng-app="myApp">
	<%= yield %>

</body>
</html>

app/STalent/app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>STalent</title>
  <meta charset="UTF-8"/>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<link href="http://fonts.googleapis.com/css?family=Roboto:500,400italic,100,300,500italic,300italic,400" rel="stylesheet" type="text/css"/>
	<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0"/>
	<%= csrf_meta_tags %>
</head>
<body ng-app="myApp">
	<div class="LayoutDashboard">
		<%= render "layouts/header" %>
		<%= yield %>
		<%= render "layouts/footer" %>
	</div>
</body>
</html>